CREATE TABLE ETABLISSEMENT(
   IDETABLISSEMENT INT,
   SIRET VARCHAR(20),
   SIREN VARCHAR(10),
   NIC VARCHAR(5),
   SIREN_BIENFORME LOGICAL,
   LIBELLE VARCHAR(200),
   CLUSTER_LIBELLE INT,
   ADRESSE VARCHAR(200),
   CODE_POSTAL VARCHAR(20),
   DEPARTEMENT VARCHAR(2),
   CP_COMMUNE VARCHAR(3),
   COMMUNE VARCHAR(100),
   GEORES_LAT DOUBLE,
   GEORES_LON DOUBLE,
   NUMERO_AGREMENT VARCHAR(50),
   EST_AGREMENTE LOGICAL,
   PRIMARY KEY(IDETABLISSEMENT)
);

CREATE TABLE ACTIVITE(
   IDACTIVITE INT,
   LIBELLE_ACTIVITE VARCHAR(200),
   PRIMARY KEY(IDACTIVITE)
);

CREATE TABLE INSPECTION(
   IDINSPECTION INT,
   NUMERO_INSPECTION VARCHAR(20),
   DATE_INSPECTION DATE,
   SYNTHESE_EVAL VARCHAR(50),
   IDETABLISSEMENT INT NOT NULL,
   IDACTIVITE INT NOT NULL,
   PRIMARY KEY(IDINSPECTION),
   FOREIGN KEY(IDETABLISSEMENT) REFERENCES ETABLISSEMENT(IDETABLISSEMENT),
   FOREIGN KEY(IDACTIVITE) REFERENCES ACTIVITE(IDACTIVITE)
);
